# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest]
        node-version: [16, 18, 20]
    name: Node.js ${{ matrix.node-version }} Test on ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          if [ "${{ matrix.node-version }}" = "16" ]; then
            npm install eslint@8.56.0 @eslint/eslintrc@2.1.4 @eslint/js@8.56.0
          fi
          npm install
      - run: npm run lint
      # - uses: codecov/codecov-action@v3
      #   with:
      #     name: codecov-node-koapp # optional
      #     fail_ci_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)
